services:
  # 1. The Database Service
  db:
    image: docker.io/postgres:15-alpine
    container_name: clean_arch_db
    restart: always
    environment:
      # These must match the credentials in your .env file
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=clean_arch_db
    ports:
      # Maps port 5432 inside container to port 5432 on your machine
      # This allows your local Python app to connect via localhost:5432
      - "5432:5432"
    volumes:
      # Persist data so it survives container restarts
      - postgres_data:/var/lib/postgresql/data

  # 2. The Application Service
  app:
    build: .
    container_name: clean_arch_app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/clean_arch_db
      - SECRET_KEY=supersecretkey
    depends_on:
      - db
    restart: always


volumes:
  postgres_data: